georgewfraser/java-language-server

README.md
This adds a description how to setup gradle to generate `javaconfig.json` and `classpath.txt`.
=> Describe gradle setup

pom.xml
In order to use the project as a language server easily, it should be runnable and be able to be started as a process.
This change makes the fat jar generated by `mvn package` under `out/fat-jar.jar` runnable
=> Make the generated fat jar runnable

README.md
Here is a quick way to add support for builds that use sbt (e.g. Play Framework projects). Until sbt support is builtin this will allow users to modify their own projects to use the extension. 
Great extension by the way, thanks!
=> Add basic support for SBT based builds

scripts/install.sh
The README states that this file is directly executable. But it is not without this line.
=> Shebang line in install.sh

src/main/java/org/javacs/JavaTextDocumentService.java
When only one change is happened, and `change.getRange() == null`, so a new version content will be put into activeDocuments.
However, later `newText` will still overwrite this version. Unfortunately, in this case, `newText` will be `existing.content`.
So in this case, the existing content will be put into activeDocuments in the end.
=> Fix issue of `didChange` for null range change.

src/main/java/module-info.java, src/main/java/org/javacs/lsp/DocumentLinkParams.java, src/main/java/org/javacs/lsp/LSP.java, src/main/java/org/javacs/lsp/LanguageServer.java
I added an exports to the module-info.java.  This lets the APIs for LSP be exported but keep the Java server implementation hidden from the outside.  
I've also added support for the documentLink request.  (See https://github.com/secondsun/wla-language-server/blob/master/src/main/java/net/saga/snes/dev/wlalanguageserver/WLALanguageServer.java#L81)
=> Exporting lsp and adding documentLink

src/main/java/org/javacs/Main.java
What
===
Add '--quiet' option for standalone usage. When provided the logger will
be turned off resulting in no information writing to stderr.
Why
===
When using standalone with IDEs like vim and plugins like vim-lsc the
stderr of the command will be outputted into the terminal. This tool is
pretty noisy and writes a lot of information which is great for
development of the tool but not when using it day-to-day.
=> Add '--quiet' option for standalone usage

README.md
Add installation instructions for vim using the vim plugin vim-lsc.
This tool works great in vim but it isn't straight forward setting it
up. These instructions will help others get off the ground using this
tool with vim.
- These instructions assume #79 is merged that adds `--quiet`.
- I added the call out that this server is using version 3.0 of the
language server protocol. Mentioning that isn't really required,
but I think it's helpful to call out because there are several tools
out there now that only interact with v2.0 servers. The main
difference being that the `initialized` event is never sent which
causes some servers, e.g. this one, not to be in the right state.
=> Add installation instructions for vim

src/main/java/org/javacs/lsp/LSP.java
Respond to shutdown request with an empty result.
The server does not respond to the shutdown request. Clients expect a
response to the shutdown request before they issue the exit request.
This is to give the server time to shutdown properly before the client
also shuts down. In IDE clients that follow this pattern properly, e.g.
vim-lsc, it can cause the IDE to lock up and wait for a response until a
timeout occurs. It's possible this is a problem in multi-threaded IDEs
(e.g. VS Code) too and the effects of it may be hidden by background
threads.
The response has been implemented based off the LSP v3.0 specification.
The result in the response is null.
https://microsoft.github.io/language-server-protocol/specification#shutdown
=> Fix bug where server blocks clients during shutdown

javaLsFlag.txt, src/main/java/org/javacs/Docs.java, src/main/java/org/javacs/Lib.java
Remove src.zip and get it from the path pointed to by the JAVA_HOME
environment variable.
When using this tool standalone the lib/src.zip file doesn't seem to be
packaged inside what is jlinked which causes exceptions on startup. It
also seems odd to package src.zip inside the tool when Java JDK
installations come with src, and in the event they don't (e.g.  OpenJDK
on Debian) they can be easily installed using the distros built in
package manager.
As a side note the src.zip licensing is ambiguous to me and it's not
clear from any other documentation in this repository how it is being
licensed. I assume it is properly licensed to have been included, but
regardless removing any licensing ambiguity from the tool seems ideal
for those using it.
- …
=> Remove src.zip and get it from JAVA_HOME

src/main/java/org/javacs/Lib.java
What
===
Support other locations for finding src.zip so that it is found it if
lives at either:
- JAVA_HOME/lib/src.zip
- JAVA_HOME/src.zip
Why
===
I've observed in testing that some installations of JVMs include src.zip
in the root, others in a lib/src.zip.
=> Support other locations for finding src.zip

src/main/java/org/javacs/JavaLanguageServer.java, src/main/java/org/javacs/lsp/MarkedString.java
What
===
Display docs are plaintext in hover, instead of inside a GitHub markdown fenced markdown code block.
Why
===
Hover text can be made up of multiple MarkedStrings where a MarkedString is either plaintext, or a codeblock for a code language. Docs are usually intended to be displayed as plaintext (in markdown), with the code blocks included alongside it. The docs shouldn't be returned as one of the code blocks.
Also
===
There is also two minor improvements included with this change:
1. Plaintext docs are inserted above the code block, which presents the docs more consistently like the examples in the language server protocol specification. This also looks better in clients because the docs one-liner is often only one line, but the code blocks are often huge, so it stops the docs from …
=> Display docs correctly in hover

scripts/check_java_home.sh
Hello there.
I am using `java-language-server` for [Android](https://github.com/hsanson/vim-android) development with Vim on Parabola (Arch Linux) through the AUR [stable](https://aur.archlinux.org/packages/java-language-server/) and [git](https://aur.archlinux.org/packages/java-language-server-git/) packages.
I tried building `java-language-server` with OpenJDK 12 and it seems to be working just fine.
This PR contains a proposal to allow linking with JDK versions equal or higher than 11.
What are your thoughts? Thank you for your time.
=> Allow JDK versions higher than 11

src/main/java/org/javacs/FileStore.java
`FileStore::isJavaFile` verifies only that path name ends with `.java`. In case that path is a directory with name for example `lib.java` this cause IOException which cause that server could not initialize itself. To mitigate that this pull request additionally verifies if path point to file.
=> Correctly verify that directory witch ends with `.java` is not a java file.

README.md
This is an update to the instructions of installing the java language server on vim (issue #122).
=> changing the instructions of installing on other editors

src/main/java/org/javacs/CompileBatch.java
Specifies which JDK to use (by getting the system JDK though `JAVA_HOME` environment variable) when creating a Java Compiler in order to make the code intelligence capable on finding Java library classes that are not inside the `java-language-server` standalone copy of Java. (#124)
=> adding --system javac option to override the location of system modules

src/main/java/org/javacs/CompileBatch.java
Removing the --system javac option introduced in #129, because it breaks the LSP server for Java version < 13 (#132).
The change in #130 didn't went through, as the state of master still includes the --system option that breaks the LSP.
=> Remove --system javac option again

src/main/java/org/javacs/JavaHomeHelper.java
JavaHomeHelper:81 throws `NoSuchFileException` in `Files.list` when the
directories listed on line 60 do not exist.  Given that we return
`NOT_FOUND` if nothing is found, it seems reasonable to simple swallow
the exception and allow `NOT_FOUND` if none of the directories exist.
=> 145 Crashes on Arch Linux `NoSuchFileException: /usr/java`

src/main/java/org/javacs/completion/CompletionProvider.java
The [language server protocol spec](https://microsoft.github.io/language-server-protocol/specification#command) says that titles with commands are mandatory. My language client ([LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim/)) barfs whenever it gets completion results without a title. Fixing this makes my client work.
=> Add title to Commands sent with completion items.

src/main/java/org/javacs/markup/ErrorProvider.java
I'm getting a NullPointerException when I add a jar to the classpath and it contains some imports to other classes not available in the classpath.
This PR fixes this issue.
=> Fix NullPointerException

src/main/java/org/javacs/markup/WarnUnused.java, src/test/examples/missing-type-identifier/Sample.java, src/test/java/org/javacs/JavaLanguageServerTest.java
=> Remove warning for '<error>' text, which is added during AST generation

src/main/java/org/javacs/InferConfig.java
The aquery command will fail if some rules fail. There are also customized rules set to always fail. This will allow the command finish.
=> Allow bazel aquery failures for incorrect rule

src/main/java/org/javacs/action/CodeActionProvider.java, src/test/examples/maven-project/src/org/javacs/action/TestAddImportAnonymousClass.java, src/test/java/org/javacs/CodeActionTest.java
It seems that unresolved idents inside anonymous classes are producing
"compiler.err.cant.resolve" errors instead of
"compiler.err.cant.resolve.location". Handle them in the same way.
=> Handle compiler.err.cant.resolve for imports

pom.xml, src/main/java/org/javacs/markup/WarnNotThrown.java, src/test/examples/maven-project/src/org/javacs/warn/NotThrownConstructor.java, src/test/java/org/javacs/WarningsTest.java
WarnNotThrown didn't check the constructor invocations (visitNewClass).
This makes warnings even if it's legitimate.
In order to run a test, modules needed to be exported/opened as it's
using com.sun APIs. pom.xml is changed to specify this in `mvn test`.
=> Handle checked exception on the constructors

src/main/java/org/javacs/debug/proto/DebugAdapter.java, src/main/java/org/javacs/lsp/LSP.java, src/test/java/org/javacs/lsp/LspTest.java
Reading multibyte characters leads to corrupt FileStore and shows the wrong diagnostic.  Using the built-in method String#readNBytes helps to prevent it.
=> Fix reading multibyte characters

README.md, package.json, src/main/java/org/javacs/JavaLanguageServer.java
I am writing Java code in an environment where the source is compiled using Makefiles and Ant.  I configure my editor to explicitly tell java-language-server the correct Java class path.  Unfortunately, there's currently no way to also explicitly set the doc path.  This change adds that capability.
=> Allow docPath to be explicitly set.

README.md
I added instructions on how to add this server to KDE's Kate editor (tested on my own installation).
Also took the liberty of adding syntax highlight on both Kate and Sublime json snippets, and removed some trailing spaces left behind (well my editor did).
=> Adding Kate instructions to the README.md file

src/main/java/org/javacs/markup/ErrorProvider.java
`getEndPosition` can sometimes return `NOPOS` (`-1L`)
=> Fix out of bounds

src/main/java/org/javacs/FileStore.java, src/main/java/org/javacs/lsp/TextDocumentContentChangeEvent.java
rangeLength has been deprecated inside TextDocumentChangeEvent. Helix doesn't provide it anymore, leading the LSP to crash when using it.
This should also fix #84
=> Remove deprecated rangeLength

git_hooks/pre-commit
Linux mktemp wants at least three X characters in the template.
WIthout the Xs in the pattern, the mktemp call fails.
=> Add XXXX to a mktemp template pattern.

scripts/benchmark.sh, scripts/build.sh, scripts/download_linux_jdk.sh, scripts/download_mac_jdk.sh, scripts/download_windows_jdk.sh, scripts/format.sh, scripts/gen_proto.sh, scripts/link_linux.sh, scripts/link_mac.sh, scripts/link_windows.sh
It's recommended to point the shebang for bash scripts to `/usr/bin/env bash` instead of `/bin/bash` to account for systems that may have a non-standard binary layout, like, e.g., NixOS. This patch adjust the install scripts to properly handle these cases.
=> fix: Adjust shebang to point to `/usr/bin/env bash`

pom.xml
Hi!
I recently bumped the Maven version in Nixpgks (https://github.com/NixOS/nixpkgs/pull/238746) and ran into some small but annoying manual effort w.r.t. the this package. The issue is that this package is packaged using the [double invocation](https://ryantm.github.io/nixpkgs/languages-frameworks/maven/#double-invocation) method which unfortunately breaks if not all maven plugin versions are set explicitly.
We're extending the documentation to prevent this (https://github.com/NixOS/nixpkgs/pull/238774), but I'm reaching out to fix the packages which have already been packaged. In this PR, we explicitly set the versions of a few plugins which hadn't had their versions set explicitly before and add a check with the enforcer plugin to make sure this won't accidentally break in the future. …
=> Enforce explicit plugin versions

src/main/java/org/javacs/hover/HoverProvider.java
It used to show docs of the enclosing class.
=> Fix hover docs for class fields

src/main/java/org/javacs/navigation/FindReferences.java, src/test/examples/maven-project/src/org/javacs/example/VarTypeReferences.java, src/test/java/org/javacs/FindReferencesTest.java
It is possible that the matching type does not appear directly in the AST, e.g. when a type is referenced with "var". This patch fixes the issue by skipping such matches.
Fixes #297.
=> Fix IndexOutOfBoundException on finding references

lib/extension.ts, src/main/java/org/javacs/JavaLanguageServer.java, src/main/java/org/javacs/lsp/LSP.java, src/main/java/org/javacs/lsp/RegistrationParams.java
- Dynamic registration for `client/capability` requests was fixed
- FileSystemWatchers was removed in favor of using dynamic registration
=> Fix for dynamic registration of capabilities

src/main/java/org/javacs/FileStore.java, src/main/java/org/javacs/StringSearch.java, src/test/examples/encoding/EncodingWindows1252.java, src/test/java/org/javacs/FileEncodingTest.java, src/test/java/org/javacs/LanguageServerFixture.java
This PR fixes the crash by ignoring any file that throws an encoding exception while its being read.
=> Fix language server crash when it encounters a file that is not UTF-8

README.md
=> Add download step

src/test/java/org/javacs/ArtifactTest.java, src/test/java/org/javacs/ClassesTest.java, src/test/java/org/javacs/CodeActionTest.java, src/test/java/org/javacs/CodeLensTest.java, src/test/java/org/javacs/CompletionsScopesTest.java, src/test/java/org/javacs/CompletionsTest.java, src/test/java/org/javacs/FileEncodingTest.java, src/test/java/org/javacs/FileStoreTest.java, src/test/java/org/javacs/FindReferencesTest.java, src/test/java/org/javacs/FindSrcZipTest.java, src/test/java/org/javacs/GotoTest.java, src/test/java/org/javacs/HoverTest.java, src/test/java/org/javacs/IncrementalCompileTest.java, src/test/java/org/javacs/InferBazelConfigTest.java, src/test/java/org/javacs/InferConfigTest.java, src/test/java/org/javacs/MarkdownHelperTest.java, src/test/java/org/javacs/SearchTest.java, src/test/java/org/javacs/SemanticColorsTest.java, src/test/java/org/javacs/SignatureHelpTest.java, src/test/java/org/javacs/SourceFileManagerTest.java, src/test/java/org/javacs/StringSearchTest.java, src/test/java/org/javacs/WarningsTest.java, src/test/java/org/javacs/lsp/LanguageServerTest.java, src/test/java/org/javacs/lsp/LspTest.java, src/test/java/org/javacs/rewrite/RewriteTest.java
I replaced all usages of `org.junit.Assert.assertThat` with the recommended `org.hamcrest.MatcherAssert.assertThat`.
This change updates the import statements in the affected test files.
=> Refactor: Replace deprecated org.junit.Assert.assertThat
